# Create Python App
# by Mnebuerquo
# https://github.com/mnebuerquo/create-python-app
# Please keep the above link in place if you are using this in your project!

version: '3'
services:
  lint:
    build: "./dockerdev/lint"
    volumes:
        - ".:/usr/src/app:ro"

  pytest:
    build:
      context: "."
      dockerfile: "./dockerdev/pytest/Dockerfile"
    volumes:
        - ".:/usr/src/app:ro"

  watch:
    build:
      context: "./dockerdev/watch"
      dockerfile: "./dockerdev/watch/Dockerfile"
    volumes:
        - ".:/usr/src/app"

  dev:
    build:
      context: "."
      dockerfile: "./dockerdev/dev/Dockerfile"
    volumes:
        - ".:/usr/src/app"
        - "./logs/:/usr/src/app/logs/"

  prod:
    build:
      context: .
      dockerfile: "./dockerdev/prod/Dockerfile"
