# Create Python App
# by Mnebuerquo
# https://github.com/mnebuerquo/create-python-app
# Please keep the above link in place if you are using this in your project!

# Usage: 
# docker-compose build
# docker-compose run lint
# docker-compose run pytest
# docker-compose run watch
# docker-compose run dev
# docker-compose run prod

# Environment:
# This will not work without certain environment variables set!
# PROJECT: this is the path to the project you want to run or test
# DOCKERDEV: this is the path where the docker-compose.yml lives

version: '3'
services:

  lint:
    build: ./lint
    volumes:
        - "${PROJECT:-.}:/usr/src/app:ro"
    entrypoint:
        - flake8
        - --append-config=/usr/lint/flake8.ini

  format:
    build: ./lint
    volumes:
        - "${PROJECT:-.}:/usr/src/app"
    entrypoint:
        - autopep8
        - --in-place
        - --recursive
        - --aggressive

  pytest:
    build:
      context: "${PROJECT:-.}"
      dockerfile: "${DOCKERDEV:-./dockerdev}/pytest/Dockerfile"
    volumes:
        - "${PROJECT:-.}:/usr/src/app"

  watch:
    build:
      context: ./watch
    volumes:
        - "${PROJECT:-.}:/usr/src/app"

  dev:
    build:
      context: "${PROJECT:-.}"
      dockerfile: "${DOCKERDEV:-./dockerdev}/dev/Dockerfile"
    volumes:
        - "${PROJECT:-.}:/usr/src/app"
        - "${PROJECT:-.}/logs/:/usr/src/app/logs/"

  prod:
    build:
      context: "${PROJECT:-.}"
      dockerfile: "${DOCKERDEV:-./dockerdev}/prod/Dockerfile"
